Update changelog for draft version with all current changes.
icpc/ccs-specs pull request #137
Opened 2023-03-13 20:40 UTC by nickygerritsen

2023-03-13 20:41 UTC, niemela approved these changes

2023-03-13 20:52 UTC, niemela approved these changes

2023-03-13 21:05 UTC, eldering requested changes

2023-03-13 21:05 UTC, eldering commented on readme.md
> +* Changed `team_id` (of type `ID`) to `team_ids` (of type `array of ID`) on the Person endpoint.
For consistency with the first change line:
```suggestion
* Changed `team_id` (of type `ID`) to `team_ids` (of type `array of ID`) in the Person endpoint.
```

2023-03-13 21:05 UTC, eldering commented on readme.md
> +* Added a `contest_thaw` capability to thaw a contest via a PUT request.
```suggestion
* Added a `contest_thaw` capability to thaw a contest via a PATCH request.
```

2023-03-15 03:06 UTC, niemela approved these changes

2023-03-15 19:58 UTC, eldering approved these changes

2023-03-15 19:59 UTC, merged